import { describe, expect, it } from 'vitest';
import { renderToString } from 'react-dom/server';
import App from '../App';

describe('App analyst console', () => {
  it('renders the analyst console sections', () => {
    const html = renderToString(<App />);

    expect(html).toContain('Wayfarer analyst console');
    expect(html).toContain('Primary workflow');
    expect(html).toContain('Population Summary');
    expect(html).toContain('Selected User Summary');
    expect(html).toContain('Rater signal profile');
    expect(html).toContain('Cohort-local island affinity');
    expect(html).toContain('Discovery Routing');
    expect(html).toContain('Reviewer Archetype Recovery');
    expect(html).toContain('Debug Data');
    expect(html).toContain('Turn Summary');
    expect(html).toContain('Novice');
    expect(html).toContain('Expert');
    expect(html).toContain('Read path');
    expect(html).toContain('Demo narrative');
    expect(html).toContain('Curator notes');
    expect(html).toContain('Drilldown targets');
    expect(html).toContain('Pinned reference');
    expect(html).toContain('Turn behavior / Dynamic settings');
    expect(html).toContain('Rating count policy');
    expect(html).toContain('Organic Exploration');
    expect(html).toContain('Bootstrap Ratings / User');
    expect(html).toContain('Participating Users / Turn');
    expect(html).toContain('Organic Ratings / User');
    expect(html).toContain('Turns to Run');
    expect(html).toContain('System use case');
    expect(html).toContain('Player journey');
    expect(html).toContain('Shared steps');
    expect(html).toContain('Expected system result');
    expect(html).toContain('Expected player result');
    expect(html).toContain('Open About');
    expect(html).toContain('Hidden generator archetype');
    expect(html).toContain('Take 1 Turn');
    expect(html).toContain('Export Current Simulation JSON');
    expect(html).toContain('Import Scenario JSON');
    expect(html).toContain('Turns to Run');
    expect(html).toContain('First-time walkthrough');
    expect(html).not.toContain('Model Explanation');
    expect(html).not.toContain('Island Comparison');
    expect(html).not.toContain('Pseudo-Cohort Reports');
    expect(html).not.toContain('Passive');
    expect(html).not.toContain('Active Discovery Turns');
  });
});
