import { describe, expect, it } from 'vitest';
import { renderToString } from 'react-dom/server';
import App from '../App';

describe('App analyst console', () => {
  it('renders the analyst console sections and demo-first novice setup', () => {
    const html = renderToString(<App initialGuidanceMode="novice" />);

    expect(html).toContain('Wayfarer analyst console');
    expect(html).toContain('Run Context');
    expect(html).toContain('Primary workflow');
    expect(html).toContain('Scenario setup');
    expect(html).toContain('Golden Demo');
    expect(html).toContain('Population Summary');
    expect(html).toContain('Selected User Summary');
    expect(html).toContain('Rater signal profile (internal)');
    expect(html).toContain('Current signal-weight proxy');
    expect(html).toContain('Cohort-local island affinity');
    expect(html).toContain('Discovery Routing');
    expect(html).toContain('Confidence Growth');
    expect(html).toContain('Turn Recap');
    expect(html).toContain('Reviewer Archetype Recovery');
    expect(html).toContain('Turn Summary');
    expect(html).toContain('Novice');
    expect(html).toContain('Expert');
    expect(html).toContain('Novice keeps the instructional rails open while expert exposes the resolved controls.');
    expect(html).toContain('Guided path');
    expect(html).toContain('Guided paths');
    expect(html).toContain('Drilldown targets');
    expect(html).toContain('Pinned reference');
    expect(html).toContain('Scenario preset');
    expect(html).toContain('Simulation JSON');
    expect(html).toContain('Golden Demo');
    expect(html).toContain('Open demo report');
    expect(html).toContain('Presentation-ready readout for the current Golden Demo state.');
    expect(html).toContain('Inspection / dashboard panels');
    expect(html).not.toContain('Bootstrap Ratings / User');
    expect(html).not.toContain('Rating count policy');
    expect(html).not.toContain('Organic Ratings / User');
    expect(html).not.toContain('Tag Alignment');
    expect(html).not.toContain('Rating Alignment');
    expect(html).not.toContain('Participating Users / Turn');
    expect(html).not.toContain('Turns to Run');
    expect(html).toContain('Open About');
    expect(html).toContain('Show debug');
    expect(html).toContain('Execute Scenario');
    expect(html).toContain('Take 1 Turn');
    expect(html).toContain('Timing log');
    expect(html).toContain('Export');
    expect(html).toContain('Import');
    expect(html).toContain('Selected user');
    expect(html).toContain('Discovery Signal');
    expect(html).toContain('Focus island');
    expect(html).toContain('Top routed island');
    expect(html).toContain('Participating users / turn');
    expect(html).toContain('For a concrete proof example, select an island and inspect Truth Alignment.');
    expect(html).toContain('Turn <!-- -->0');
    expect(html).toContain('Scenario:');
    expect(html).toContain('Mode:');
    expect(html).toContain('Participation:');
    expect(html).toContain('Rating counts:');
    expect(html).toContain('Routing:');
    expect(html).toContain('Navigation Tutorial');
    expect(html).toContain('Guided path overview');
    expect(html).toContain('System framing');
    expect(html).toContain('Experience framing');
    expect(html).toContain('Path steps');
    expect(html).toContain('Success criteria');
    expect(html).toContain('Maintenance note');
    expect(html).not.toContain('Model Explanation');
    expect(html).not.toContain('Island Comparison');
    expect(html).not.toContain('Pseudo-Cohort Reports');
    expect(html).not.toContain('Debug Data');
    expect(html).not.toContain('Passive');
    expect(html).not.toContain('Active Discovery Turns');
    expect(html).not.toContain('False Positives Preview');
    expect(html).not.toContain('False Negatives Preview');
    expect(html).toContain('These scenarios are defined in src/data/scenario-catalog.json. Edit that JSON to change the named presets.');
  });

  it('renders expert preset controls', () => {
    const html = renderToString(<App initialGuidanceMode="expert" />);

    expect(html).toContain('Scenario preset');
    expect(html).toContain('Scenario setup');
    expect(html).toContain('Bootstrap Ratings / User');
    expect(html).toContain('Tag Alignment');
    expect(html).toContain('Rating Alignment');
    expect(html).toContain('Current signal-weight proxy');
    expect(html).toContain('Turn behavior / Dynamic settings');
    expect(html).toContain('Open demo report');
    expect(html).toContain('Turn Mode');
    expect(html).toContain('Participation Model');
    expect(html).toContain('Turns to Run');
    expect(html).toContain('Seed on execute');
    expect(html).toContain('Execute Scenario');
    expect(html).toContain('Expert keeps the same run-context choices visible and exposes the resolved controls.');
  });
});
